/**
 * Copies the locale namespaces the API needs into a generated TypeScript file.
 *
 * The web app's `en.json` / `pl.json` are the single source of truth for every
 * string in Kosvia. Most of them only ever render in a browser, but three
 * namespaces also have to render on the server: the offline AI provider writes
 * prose, and prose has to be in the reader's language. Rather than keep a
 * second hand-maintained copy in sync by discipline, this script copies them,
 * and `phrases.generated.spec.ts` fails the build if the copy has drifted.
 *
 *   node scripts/sync-phrases.mjs          writes the file
 *   node scripts/sync-phrases.mjs --check  exits 1 if it is out of date
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const localesDir = resolve(here, '../../web/i18n/locales');
const target = resolve(here, '../src/common/i18n/phrases.generated.ts');

/** MATCH and GENERATED are emitted by the server; VOCAB renders their params. */
const NAMESPACES = ['MATCH', 'GENERATED', 'VOCAB'];
const LOCALES = ['en', 'pl'];

export function build() {
  const messages = {};
  for (const locale of LOCALES) {
    const all = JSON.parse(readFileSync(resolve(localesDir, `${locale}.json`), 'utf8'));
    messages[locale] = Object.fromEntries(NAMESPACES.map((ns) => [ns, all[ns]]));
  }
  return [
    '// AUTO-GENERATED by scripts/sync-phrases.mjs — do not edit by hand.',
    '// Source: apps/web/i18n/locales/{en,pl}.json',
    '// Regenerate with `npm run sync:phrases -w @kosvia/api`.',
    '',
    `export const PHRASES = ${JSON.stringify(messages, null, 2)} as const;`,
    '',
  ].join('\n');
}

const contents = build();
if (process.argv.includes('--check')) {
  const current = readFileSync(target, 'utf8');
  if (current !== contents) {
    console.error('phrases.generated.ts is out of date — run `npm run sync:phrases -w @kosvia/api`.');
    process.exit(1);
  }
  console.log('phrases.generated.ts is up to date.');
} else {
  writeFileSync(target, contents);
  console.log(`wrote ${target}`);
}
